In [2]:
#IMPORTACAO DAS BIBLIOTECAS

import pandas as pd
import numpy as np

In [3]:
#IMPORTACAO CVS
df_customers = pd.read_csv("customers_raw.csv")
df_customers.head()

,customer_id,company_name,industry,company_size,employees,state,city,customer_since,acquisition_channel,service_type,contract_type,payment_method
0,C00001,Empresa 0001,Indústria,Média,511,RJ,Rio de Janeiro,2022-02-21,Site,Consultoria,Mensal,Transferência
1,C00002,Empresa 0002,Tecnologia,Pequena,486,SP,Santos,2022-03-03,Parceiro,Consultoria,Mensal,Transferência
2,C00003,Empresa 0003,Financeiro,Média,23,PR,Curitiba,2024-07-08,LinkedIn,Tecnologia,Anual,Boleto
3,C00004,Empresa 0004,Tecnologia,Pequena,788,PR,Curitiba,2023-11-21,Evento,Tecnologia,Anual,Pix
4,C00005,Empresa 0005,Tecnologia,Média,171,PE,Jaboatão dos Guararapes,2025-01-03,Parceiro,Tecnologia,Mensal,Pix

In [4]:
#DIAGNOSTICO DE QUALIDADE DOS DADOS
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          3000 non-null   object
 1   company_name         3000 non-null   object
 2   industry             3000 non-null   object
 3   company_size         3000 non-null   object
 4   employees            3000 non-null   int64
 5   state                3000 non-null   object
 6   city                 2950 non-null   object
 7   customer_since       3000 non-null   object
 8   acquisition_channel  3000 non-null   object
 9   service_type         2966 non-null   object
 10  contract_type        2970 non-null   object
 11  payment_method       2955 non-null   object
dtypes: int64(1), object(11)
memory usage: 281.4+ KB

In [5]:
#DIAGNOSTICAR QUALIDADE DOS DADOS
#VERIFICAR VALORES NULOS
df_customers.isnull().sum()

customer_id             0
company_name            0
industry                0
company_size            0
employees               0
state                   0
city                   50
customer_since          0
acquisition_channel     0
service_type           34
contract_type          30
payment_method         45
dtype: int64

In [6]:
# TRATAMENTO DOS VALORES NULOS

df_customers["city"] = df_customers["city"].fillna("Não informado")
df_customers["service_type"] = df_customers["service_type"].fillna("Não informado")
df_customers["contract_type"] = df_customers["contract_type"].fillna("Não informado")
df_customers["payment_method"] = df_customers["payment_method"].fillna("Não informado")

# VALIDAR
df_customers.isnull().sum()

customer_id            0
company_name           0
industry               0
company_size           0
employees              0
state                  0
city                   0
customer_since         0
acquisition_channel    0
service_type           0
contract_type          0
payment_method         0
dtype: int64

In [7]:
#PADRONIZAR COLUNAS 

colunas_texto = [
    "company_name",
    "industry",
    "company_size",
    "state",
    "city",
    "acquisition_channel",
    "service_type",
    "contract_type",
    "payment_method"
]

for coluna in colunas_texto:
    df_customers[coluna] = df_customers[coluna].str.strip().str.title()

df_customers.head(10)

,customer_id,company_name,industry,company_size,employees,state,city,customer_since,acquisition_channel,service_type,contract_type,payment_method
0,C00001,Empresa 0001,Indústria,Média,511,Rj,Rio De Janeiro,2022-02-21,Site,Consultoria,Mensal,Transferência
1,C00002,Empresa 0002,Tecnologia,Pequena,486,Sp,Santos,2022-03-03,Parceiro,Consultoria,Mensal,Transferência
2,C00003,Empresa 0003,Financeiro,Média,23,Pr,Curitiba,2024-07-08,Linkedin,Tecnologia,Anual,Boleto
3,C00004,Empresa 0004,Tecnologia,Pequena,788,Pr,Curitiba,2023-11-21,Evento,Tecnologia,Anual,Pix
4,C00005,Empresa 0005,Tecnologia,Média,171,Pe,Jaboatão Dos Guararapes,2025-01-03,Parceiro,Tecnologia,Mensal,Pix
5,C00006,Empresa 0006,Varejo,Média,173,Sp,São Paulo,2025-09-16,Indicação,Gestão,Anual,Transferência
6,C00007,Empresa 0007,Saúde,Média,439,Rs,Caxias Do Sul,2022-11-30,Indicação,Dados,Mensal,Boleto
7,C00008,Empresa 0008,Saúde,Grande,1150,Pe,Recife,2024-02-17,Evento,Consultoria,Mensal,Pix
8,C00009,Empresa 0009,Saúde,Pequena,442,Rs,Caxias Do Sul,2024-04-01,Site,Gestão,Anual,Transferência
9,C00010,Empresa 0010,Varejo,Pequena,1159,Mg,Uberlândia,2023-06-27,Parceiro,Gestão,Anual,Cartão

In [ ]:
#CORRIGIR TIPO DE COLUNA
df_customers["customer_since"] = pd.to_datetime(
    df_customers["customer_since"],
    format="mixed",
    dayfirst=True
)
#VALIDAR
df_customers.info()

In [9]:
df_customers["customer_since"].head(10)

0   2022-02-21
1   2022-03-03
2   2024-07-08
3   2023-11-21
4   2025-01-03
5   2025-09-16
6   2022-11-30
7   2024-02-17
8   2024-04-01
9   2023-06-27
Name: customer_since, dtype: datetime64[ns]